# Generated by Django 2.2.27 on 2024-09-14 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20240914_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorpoint',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
        ),
    ]
