# Generated by Django 2.2.27 on 2024-10-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20240920_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorcategory',
            name='is_delete',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitorpoint',
            name='is_delete',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
